Fix TypeError "unsupported type for timedelta minutes component: str"
The following error was caused because the env variable FILE_LIFE_SPAN was not parsed to integer:

  File "/mari-data/./app.py", line 494, in request_env_data
    file_end_of_life = (datetime.now(pytz.utc) + timedelta(minutes=FILE_LIFE_SPAN))
TypeError: unsupported type for timedelta minutes component: str